#!/bin/bash
mkdir $1
mkdir $1/src

cat >$1/$1.cabal <<EOL
name:                   $1
version:                0.1.0.0
build-type:             Simple
cabal-version:          >=1.10

executable $1
  hs-source-dirs:       src
  main-is:              Main.hs
  default-language:     Haskell2010
  ghc-options:          -Wall -Werror -fno-warn-missing-signatures -fno-warn-partial-type-signatures
  build-depends:        base
EOL

cat >$1/Setup.hs <<EOL
import Distribution.Simple
main = defaultMain
EOL

cat >$1/src/Main.hs <<EOL
module Main where

main :: IO ()
main = do
  putStrLn "hello world"
EOL

cat >$1/run.sh <<EOL
#!/usr/bin/env bash

stack build &&
stack exec $1
EOL
chmod +x $1/run.sh

cd $1
stack init

git init
git add .
git commit -m "Initial setup"
