#!/usr/bin/env bash

if [ -z $1 ]
then
  echo "Must provide project name, will do nothing."
  exit
fi

stack new $1 ~/Code/other/misc/haskell-stack-templates/minimal.hsfiles

cd $1
chmod +x run.sh

git init
git add .
git commit -m "Create project"
